lib/manager/web/router.ex
defmodule Manager.Web.Router do
  use Manager.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :with_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Manager.Web.Auth.CurrentUser
  end

  pipeline :login_required do
    plug Guardian.Plug.EnsureAuthenticated, handler: Manager.Web.Auth.GuardianErrorHandler
  end

  pipeline :admin_required do
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Manager.Web do
    pipe_through [:browser, :with_session] # Use the default browser stack
    get "/", PageController, :index

    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]

    scope "/" do
      pipe_through [:login_required]
      get "/users/edit", UserController, :edit
      put "/users/update", UserController, :update
      get "/sessions/logout", SessionController, :delete

      scope "/admin", Admin, as: :admin do
        pipe_through [:admin_required]
      end
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Manager.Web do
  #   pipe_through :api
  # end
end

lib/manager/web/controllers/page_controller.ex
defmodule Manager.Web.PageController do
  use Manager.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

lib/manager/web/controllers/session_controller.ex
defmodule Manager.Web.SessionController do
  use Manager.Web, :controller

  plug :scrub_params, "session" when action in ~w(create)a

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"email" => email, "password" => password}}) do
    case Manager.Web.Auth.login_by_email_and_pass(conn, email, password) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "You’re now signed in!")
        |> redirect(to: page_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid email/password combination")
        |> render("new.html")
     end
  end

  def delete(conn, _) do
    conn
    |> Manager.Web.Auth.logout
    |> put_flash(:info, "You're now signed out!")
    |> redirect(to: page_path(conn, :index))
  end
end

lib/manager/web/controllers/user_controller.ex
defmodule Manager.Web.UserController do
  use Manager.Web, :controller

  alias Manager.Accounts

  plug :scrub_params, "user" when action in [:create, :update]

  def action(conn, _) do
    apply(__MODULE__, action_name(conn),
          [conn, conn.params, conn.assigns.current_user])
  end

  def new(conn, _params, _current_user) do
    changeset = Accounts.change_user(%Manager.Accounts.User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}, _current_user) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> Manager.Web.Auth.login(user)
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: page_path(conn, :index))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def edit(conn, _params, current_user) do
    changeset = Accounts.change_user(current_user)
    render(conn, "edit.html", user: current_user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}, _current_user) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end
end

lib/manager/web/views/error_view.ex
defmodule Manager.Web.ErrorView do
  use Manager.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/manager/web/views/layout_view.ex
defmodule Manager.Web.LayoutView do
  use Manager.Web, :view
end

lib/manager/web/views/page_view.ex
defmodule Manager.Web.PageView do
  use Manager.Web, :view
end

lib/manager/web/views/session_view.ex
defmodule Manager.Web.SessionView do
  use Manager.Web, :view
end

lib/manager/web/views/user_view.ex
defmodule Manager.Web.UserView do
  use Manager.Web, :view
end

lib/manager/web/templates/layout/_flash.html.eex
<%= if get_flash(@conn, :info) do %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= get_flash(@conn, :info) %>
  </div>
<% end %>
<%= if get_flash(@conn, :error) do %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= get_flash(@conn, :error) %>
  </div>
<% end %>

lib/manager/web/templates/layout/_menu.html.eex
<%= active_link(@conn, "Home", to: "/", wrap_tag: :li) %>
<%= if @current_user do %>
  <li class="dropdown">
    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= Manager.Accounts.User.display_name(@current_user) %> <span class="caret"></span></a>
    <ul class="dropdown-menu">
      <li><%= link "Settings", to: user_path(@conn, :edit) %></li>
      <li role="separator" class="divider"></li>
      <li><%= link "Sign out", to: session_path(@conn, :delete) %></li>
    </ul>
  </li>
<% else %>
  <%= active_link(@conn, "Sign In", to: session_path(@conn, :new), wrap_tag: :li) %>
  <%= active_link(@conn, "Sign Up", to: user_path(@conn, :new), wrap_tag: :li) %>
<% end %>

lib/manager/web/templates/layout/_navigation.html.eex
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">👨‍💻 Manager</a>
    </div>
    <div class="collapse navbar-collapse" id="main-menu">
      <ul class="nav navbar-nav navbar-right">
        <%= render "_menu.html", conn: @conn, current_user: @current_user %>
      </ul>
    </div>
  </div>
</nav>

lib/manager/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Manager</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "_navigation.html", conn: @conn, current_user: @current_user %>

    <%= render "_flash.html", conn: @conn %>

    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/manager/web/templates/page/index.html.eex
<div class="container section">
  <%= if @current_user do %>
    <div class="page-header no-pad-top">
      <h1 class="no-pad-top"><small>Hello</small><br /><%= Manager.Accounts.User.display_name(@current_user) %></h1>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Your Information</h3>
          </div>
          <table class="table">
            <tbody>
              <tr>
                <th scope="row">First Name</th>
                <td><%= @current_user.first_name %></td>
              </tr>
              <tr>
                <th scope="row">Last Name</th>
                <td><%= @current_user.last_name %></td>
              </tr>
              <tr>
                <th scope="row">Email</th>
                <td><%= @current_user.email %></td>
              </tr>
              <%= if @current_user.hours do %>
                <tr>
                  <th scope="row">Hours</th>
                  <td><%= @current_user.hours %></td>
                </tr>
              <% end %>
              <%= if @current_user.efficiency do %>
                <tr>
                  <th scope="row">Efficiency</th>
                  <td><%= Float.round(Decimal.to_float(@current_user.efficiency) * 100, 2) %>%</td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% else %>
    <div class="page-header no-pad-top">
      <h1 class="no-pad-top">👨‍💻 Manager <small>Manage work hours.</small></h1>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Sign In</h3>
          </div>
          <div class="panel-body">
            <%= render Manager.Web.SessionView, "form.html", conn: @conn, action: session_path(@conn, :create) %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

lib/manager/web/templates/session/form.html.eex
<%= form_for @conn, @action, [as: :session], fn f -> %>
<div class="form-group">
  <%= label f, :email, class: "control-label" %>
  <%= text_input f, :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= label f, :password, class: "control-label" %>
  <%= password_input f, :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>

lib/manager/web/templates/session/new.html.eex
<div class="container section">
  <div class="page-header no-pad-top">
    <h1 class="no-pad-top">Sign In <small>Please enter your email address and password.</small></h1>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
          <%= render "form.html", conn: @conn, action: session_path(@conn, :create) %>
    </div>
  </div>
</div>

lib/manager/web/templates/user/edit.html.eex
<div class="container section">
  <div class="page-header no-pad-top">
    <h1 class="no-pad-top">Settings <small>Edit your account information.</small></h1>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-body">
          <%= render "form.html", changeset: @changeset, action: user_path(@conn, :update) %>
        </div>
      </div>
    </div>
  </div>
</div>

lib/manager/web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :first_name, class: "control-label" %>
    <%= text_input f, :first_name, class: "form-control" %>
    <%= error_tag f, :first_name %>
  </div>

  <div class="form-group">
    <%= label f, :last_name, class: "control-label" %>
    <%= text_input f, :last_name, class: "form-control" %>
    <%= error_tag f, :last_name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/manager/web/templates/user/new.html.eex
<div class="container section">
  <div class="page-header no-pad-top">
    <h1 class="no-pad-top">Create an Account <small>Please enter the following information.</small></h1>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3">
      <%= render "form.html", changeset: @changeset, action: user_path(@conn, :create) %>
    </div>
  </div>
</div>